const DATA_ELEMENTS = {
  SERVICES_TYPE: "cdDw6bEYQYW",
  DIASTOLIC_BLOOD_PRESSURE: "TThw3XArMBK",
  SYSTOLIC_BLOOD_PRESSURE: "tVPKjkXrMSB",
  HIGH_BLOOD_PRESSURE: "dPMhPYLpmAf",
  PNC_VISIT_NUMBER: "LvSuOSBXj10",
  PNC1_WITHIN_24HRS: "aKOgYalBdsF",
  PNC2_WITHIN_2_3DAYS: "Gsdu9X2Snf6",
  PNC3_WITHIN_7_14DAYS: "tNZQR6jvRXT",
  PNC_IN_6_WEEKS: "cEjAzgk2LbS",
  MOTHER_CONDITION: "ToisEDtLqvG",
  ABNORMAL_MOTHER_CONDITION: "enlOT545MWh",
  BABY_CONDITION: "RqCeGbBLxqg",
  ABNORMAL_BABY_CONDITION: "lIFt3SnsThX",
  EXCLUSIVE_BREASTFEEDING: "NLJtqep6znD",
  REASON_NOT_BREASTFEEDING: "pa18mVGyOqo",
  WHAT_TO_FEED_BABY: "C0Q8CMGzZlL",
  RECEIVED_IFA_TABLETS: "YQIcs5ULyyz",
  HOW_MANY_IFA_TABLETS: "SuURKJnCAah",
  RECEIVED_VITAMIN_B1: "kKNQjp1joRe",
  HOW_MANY_VITAMIN_B1_TABLETS: "McbAPAmGOTf",
  NEXT_APPOINTMENT_DATE: "Rg0YjOCLnsl",
  NEW_BORN_EXCLUSIVELY_BREASTFED_FROM_BIRTH_UNTIL_DISCHARGE: "nNU45OPk7Pa"
};

export { DATA_ELEMENTS };
