const DELIVERY_DETAILS_DATA_ELEMENTS = {
  SYSTOLIC_BLOOD_PRESSURE: "tVPKjkXrMSB",
  DIASTOLIC_BLOOD_PRESSURE: "TThw3XArMBK",
  HIGH_BLOOD_PRESSURE: "dPMhPYLpmAf",
  LMP_DATE: "s2Rmn9cu4Gu",
  WOMEN_AGE_GROUP: "JZlG2Tu8aTn",
  GESTATIONAL_WEEKS: "YesvM1AYsNy",
  LIVE_BIRTHS: "OcT4N2illVT",
  STILL_BIRTHS: "zM7ceGjIsy4",
  HIV_POSITIVE: "kplk714cfgO",
  HIV_POSITIVE_TREATED_WITH_ARV: "Uwzs4LSIYaE",
  COMPLICATIONS: "vewjTi8yuHW",
  SPECIFY_COMPLICATIONS: "ta5GkHIIlfx",
  HISTORY_OF_PREGNANCY: "qexx3OLahXV",
  HIV_TEST_DURING_ANC: "ibKMh3S8G0h",
  PROVIDING_HIV_COUNSELLING: "JlITr8aP0YU",
  LMP_DATE: "s2Rmn9cu4Gu",
  REMEMBER_LMP_DATE: "gNNMUdPwvaj",
  ESTIMATED_DUE_DATE: "e7HLBDcnUzz",
  GESTATIONAL_UNDER_OR_EQUAL_32_WEEKS_RECEIVED_MGSO4: "aUWThVvbzPo",
  GESTATIONAL_UNDER_OR_EQUAL_34_WEEKS_RECEIVED_CORTICOSTERIOD: "T1cNM2frSC0",
  BLOOD_LOSS: "jQ47ahFGzA1",
  BLOOD_LOSS_VOLUME: "KGsWBrGw6Kx",
  G: "x9pl4PJop26",
  P: "fm0Mge3AePX",
  A: "E4lPyETCSON",
  L: "Vny88TWPZ1I",
  CHILD_TEIS: "lYdXxom1BAG",
  MOTHER_DATE_OF_DISCHARGE: "zyZCBNbRZqm",
  MOTHER_DATE_OF_DELIVERY: "grMMOiF9fPj",
  DELIVERY_COMPLETED: "HrVnezRbhNk"
};

const ANC_DATA_ELEMENTS = {
  NUMBER_OF_ANC_VISIT: "kyclqodZVDs",
  HIV_TEST1: "KVHZNzocCD6",
  HIV_TEST2: "BGBniEmtdnp"
};
const ATTRIBUTES = {
  AGE: "tQeFLjYbqzv",
  SEX: "DmuazFb368B",
  FIRST_NAME: "IEE2BMhfoSc",
  LAST_NAME: "IBLkiaYRRL3",
  MOBILE: "RwoKpuIgMmA"
};

const INFANT_DATA_ELEMENTS = {
  PLACE_OF_BIRTH: "Y9zVpoBIXPR",
  FACILITY_OF_BIRTH: "O2aFWsqAvWr",
  TYPE_OF_DELIVERY: "gd3wK6I4rmv",
  DATE_OF_BIRTH: "grMMOiF9fPj",
  TIME_OF_BIRTH: "zNK0UUyWwiU",
  BIRTH_WEIGHT: "P1fhF8iYjm7",
  KANGAROO_MOM_CARE_IN_PRETERM_LOW_BIRTH_WEIGHT: "Z7y9JnO2lOm",
  NEWBORN_CONDITION: "PyhIX8vOSV0",
  RESUSCITATION: "a4WB9MFua6p",
  RESUSCITATION_DURATION: "VQYPL2OYJhy",
  CONGENITAL_ABNORMAL: "qV2cjmxUNFg",
  SEPSIS: "IhlyElhpgKO",
  DISTRESS_CARDIAC_DISEASE: "uAbn3HUmTzq",
  OTHER_ABNORNAL_SPECIFY: "GqzfELnr0l6",
  REFERRED_TO_HIGHER_FACILITY: "dqcrp4sJGr1",
  DATE_OF_REFERRAL: "tlBNRvqdtPC",
  REASON_FOR_REFERRAL: "tWrSKIFx9lm",
  SERVICE_LOCATION: "skhk4NL6E0y",
  SERVICE_TYPE: "cdDw6bEYQYW",
  MOTHERS_AGE_AT_DELIVERY: "oajtMHtVLWP",
  DATE_OF_DISCHARGE: "oCFF41o9q51",
  DATE_OF_DELIVERY: "grMMOiF9fPj",
  HEIGHT: "EsuDp7LMZTW"
};

const EIR_ATTRIBUTES = {
  DOB: "tQeFLjYbqzv",
  MOTHER_FIRST_NAME: "RqEyvE6zcTE",
  MOTHER_LAST_NAME: "WkHHrysFy3n",
  PROVINCE: "r8bZppSsIvR",
  DISTRICT: "oVwa5LfjnvA",
  VILLAGE: "UNiaP6Oz7Mv",
  PARENT_PHONE_NUMBER: "DcMyN6eoyFD"
};

const ANC_PROGRAM_STAGE = "IZ9GXqMAZV8";
const ANC_PROGRAM = "fflLsS1lm3g";
export { DELIVERY_DETAILS_DATA_ELEMENTS, INFANT_DATA_ELEMENTS, ATTRIBUTES, ANC_DATA_ELEMENTS, ANC_PROGRAM_STAGE, ANC_PROGRAM, EIR_ATTRIBUTES };
