export const DATA_ELEMENT_IDS = {
  EMERGENCY_PILLS: "kLUXIjugexO",
  SERVICE_AT: "DABgClNgMka",
  USER_TYPE: "v5RUPUQHZye",
  SERVICE_OPTED: "Qa3wfa8tmti",
  SERVICE_REMOVED: "GtgLN5jvIa0",
  SERVICE_REMOVED_REASON: "LZPdM0eC2CN",
  NEXT_APPOINT_DAY: "Rg0YjOCLnsl",
  NO_DISTRIBUTION: "UPGa0aJLsEX"
};
export const ATTRIBUTE_IDS = {
  AGE_IN_YEAR: "BaiVwt8jVfg"
};
