const DATA_ELEMENTS = {
  CLIENT_AGE_AT_VISIT: "fAsdukgUg2B",
  IPD_ADMISSION_DATE: "hoG021b39kR",
  IPD_MAIN_DIAGNOSIS: "Offof1MzVhF",
  IS_PREGNANT_ID: "dLIPYO8wooC",
  IPD_STATUS_AT_DISCHARGE: "UFy1pG1z42U",
  DATE_OF_DEATH: "IC1dxoLMrpc",
  OUTSIDE_PROVINCE: "NqPZMFyhtkj",
  OUTSIDE_DISTRICT: "myFEAEFK8SR",
  IPD_MAIN_DIAGNOSIS_ICD10: "vVNQoYA5RZH",
  IDC10_CAUSE_GROUP: "zwFVJMwggaH",
  IPD_TREATMENT_TYPE: "sMC8DNDLivc",
};

const ATTRIBUTES = {
  DOB: "tQeFLjYbqzv",
  SEX: "DmuazFb368B",
  IS_FOREIGNER: "DtqYqC9Xr5Z",
  IS_PROVINCE: "r8bZppSsIvR",
  IS_DISTRICT: "UNiaP6Oz7Mv",
  IS_VILLAGE: "oVwa5LfjnvA",
  VILLAGE: "UNiaP6Oz7Mv",
};

export { DATA_ELEMENTS, ATTRIBUTES };
