const eirLocales = {
  en: {
    programStage: "Program Stage",
    dueDate: "Due Date",
    birthDetails: "Birth details",
    immunization: "Immunization",
    currentAddress: "Current address",
    addressInstruction1:
      "Select a place where a child is currently living and expected to live more than 1 year",
    addressInstruction2:
      "If a child is living temporarily for less than 1 year and is expected to go back home, enter the home address",
    addressInstruction3:
      "This is about residence, not registered address on Family Book",
    childUniqueIdWarning1: "This field is auto generated by the system",
    childUniqueIdWarning2:
      "You will see the Child Unique ID in the next page after the registration is completed",
    bcgWarning:
      "BCG vaccine should be given at birthday. Are you sure the event date is correct?",
    birthWeightHigh:
      "Weight is very high. Are you sure this weight in grams is correct?",
    birthWeightLow:
      "Weight is very low. Are you sure this weight in grams is correct?",
    gestationalAgeWarning:
      "The gestational age is out of normal range. Please check.",
    gestationalAgeError:
      "The gestational age is too high! Please check if this is correct value.",
    scheduleNewEventForStage: "Schedule new event for stage",
    immunization: "Immunization",
    newEvent: "+",
    duplicateEventDate: "This day has been immunized",
    deactivateChild: "Deactivate",
    activateChild: "Active",
    deactivateChildWarning:
      "You are going to deactivate this child, all the data will be read-only and scheduled event will be removed, this action cannot be undone. Are you sure you want to continue ?",
    activateChildWarning: "Are you sure you want to re-active this child ?",
    rescheduleDate: "Reschedule due date",
    yearOfBirth: "Year of birth",
    last34ClientHealthIdDigits: "Last 3 or 4 digits of Client Health ID",
    foreignerInstruction:
      "Please tick this one if the child is living in another country",
    reportWastingStatusIsNotCorrect: "Report wasting status is not correct",
    reportStuntingStatusIsNotCorrect: "Report stunting status is not correct",
    reportUnderweightStatusIsNotCorrect:
      "Report underweight status is not correct"
  },
  lo: {
    programStage: "Program Stage",
    dueDate: "Due Date",
    birthDetails: "ລາຍລະອຽດການເກີດ",
    immunization: "ການສ້າງພູມຄຸ້ມກັນ",
    currentAddress: "ທີ່ຢູ່ປະຈຸບັນ",
    addressInstruction1:
      "ໃຫ້ເລືອກບ້ານທີ່ເດັກຢູ່ປະຈຸບັນ, ສຳລັບຜູ້ທີ່ຄາດວ່າຈະຢູ່ທີ່ດັ່ງກ່າວຫຼາຍກວ່າ 1 ປີຂື້ນໄປ",
    addressInstruction2:
      "ຖ້າເດັກຢູ່ຊົ່ວຄາວນ້ອຍກວ່າ 1 ປີ ແລະ ຄາດວ່າຈະກັບໄປຢູ່ທີ່ບ້ານຖາວອນແມ່ນໃຫ້ເລືອກບ້ານຖາວອນ",
    addressInstruction3:
      "ການເລືອກທີ່ຢູ່ຂອງເດັກອິງໃສ່ທີ່ຢູ່ຕົວຈິງ, ບໍ່ໃຫ້ອິງໃສ່ທີ່ຢູ່ຕາມປື້ມສຳມະໂນຄົວ",
    childUniqueIdWarning1: "ຫ້ອງນີ້ລະບົບຈະສ້າງໃຫ້ອັດຕະໂນມັດ",
    childUniqueIdWarning2:
      "ທ່ານຈະເຫັນລະຫັດສະເພາະເດັກຂອງເດັກນ້ອຍ ຢູ່ໃນຫນ້າຕໍ່ໄປຫຼັງຈາກການລົງທະບຽນສໍາເລັດແລ້ວ",
    bcgWarning:
      "BCG vaccine should be given at birthday. Are you sure the event date is correct?",
    birthWeightHigh:
      "Weight is very high. Are you sure this weight in grams is correct?",
    birthWeightLow:
      "Weight is very low. Are you sure this weight in grams is correct?",
    gestationalAgeWarning:
      "The gestational age is out of normal range. Please check.",
    gestationalAgeError:
      "The gestational age is too high! Please check if this is correct value.",
    scheduleNewEventForStage: "ກຳນົດເວລາເຫດການໃໝ່ສຳລັບ",
    immunization: "ການສ້າງພູມຄຸ້ມກັນ",
    newEvent: "+",
    duplicateEventDate: "This day has been immunized",
    deactivateChild: "ປິດການໃຊ້ງານ",
    activateChild: "ເປີດໃຊ້ງານ",
    deactivateChildWarning:
      "You are going to deactivate this child, all the data will be read-only and scheduled event will be removed, this action cannot be undone. Are you sure you want to continue ?",
    activateChildWarning: "ທ່ານໝັ້ນໃຈບໍວ່າທ່ານຈະເປີດໃຊ້ງານເດັກຄືນ?",
    rescheduleDate: "ປ່ຽນວັນທີນັດຄັ້ງຕໍ່ໄປ",
    yearOfBirth: "ປີເກິດ",
    last34ClientHealthIdDigits: "ເລກທ້າຍ 3 ຫລື 4 ຕົວຂອງລະຫັດສຸຂະພາບ",
    foreignerInstruction: "ກະລຸນະຕິກຖ້າຜູ້ມາຮັບວັກຊີນອາໃສຢູ່ຕ່າງປະເທດ",
    reportWastingStatusIsNotCorrect: "ຄ່ານ້ຳໜັກທຽບໃສ່ລວງສູງບໍ່ຖືກຕ້ອງ",
    reportStuntingStatusIsNotCorrect: "ຄ່າລວງສູງ/ລວງຍາວບໍ່ຖືກຕ້ອງ",
    reportUnderweightStatusIsNotCorrect: "ຄ່ານ້ຳໜັກຫຼຸດເກນມາດຕະຖານບໍ່ຖືກຕ້ອງ"
  }
};

export default eirLocales;
