const fddAdrLocales = {
  en: { childUniqueIdWarning: "This field is auto generated by the system" },
  lo: { childUniqueIdWarning: "ຫ້ອງນີ້ລະບົບຈະສ້າງໃຫ້ອັດຕະໂນມັດ" },
};

export default fddAdrLocales;
