const eirLocales = {
  en: {
    programStage: "Program Stage",
    dueDate: "Due Date",
    birthDetails: "Birth details",
    immunization: "Immunization",
    currentAddress: "Current address",
    childUniqueIdWarning: "This field is auto generated by the system",
    bcgWarning:
      "BCG vaccine should be given at birthday. Are you sure the event date is correct?",
    birthWeightHigh:
      "Weight is very high. Are you sure this weight in grams is correct?",
    birthWeightLow:
      "Weight is very low. Are you sure this weight in grams is correct?",
    gestationalAgeWarning:
      "The gestational age is out of normal range. Please check.",
    gestationalAgeError:
      "The gestational age is too high! Please check if this is correct value.",
  },
  lo: {
    programStage: "Program Stage",
    dueDate: "Due Date",
    birthDetails: "ລາຍລະອຽດການເກີດ",
    immunization: "ການສ້າງພູມຄຸ້ມກັນ",
    currentAddress: "ທີ່ຢູ່ປະຈຸບັນ",
    childUniqueIdWarning: "ຫ້ອງນີ້ລະບົບຈະສ້າງໃຫ້ອັດຕະໂນມັດ",
    bcgWarning:
      "BCG vaccine should be given at birthday. Are you sure the event date is correct?",
    birthWeightHigh:
      "Weight is very high. Are you sure this weight in grams is correct?",
    birthWeightLow:
      "Weight is very low. Are you sure this weight in grams is correct?",
    gestationalAgeWarning:
      "The gestational age is out of normal range. Please check.",
    gestationalAgeError:
      "The gestational age is too high! Please check if this is correct value.",
  },
};

export default eirLocales;
