const DATA_ELEMENTS = {
  FAMILY_PLANNING_VISIT_NUMBER: "m50M3yMLVSi",
  SERVICE_ADOPTION_AT: "U2XoYP4zDSM",
  COMPLETED_IFA_90_TABLETS: "YQIcs5ULyyz",
  EMERGENCY_PILLS: "kLUXIjugexO",
  USER_TYPE: "v5RUPUQHZye",
  SERVICE_OPTED: "Qa3wfa8tmti",
  AGE_GROUP: "JZlG2Tu8aTn",
  SERVICE_REMOVED: "GtgLN5jvIa0",
  REASON_FOR_SERVICE_REMOVED: "LZPdM0eC2CN",
  OTHER_REASON_FOR_REMOVAL: "Y0NLw2KuLFo",
  NUMBER_OF_DISTRIBUTION: "UPGa0aJLsEX",
  NEXT_APPOINTMENT_DATE: "Rg0YjOCLnsl"
};

export { DATA_ELEMENTS };
