import _ from "lodash";
import useTrackerCaptureStore from "@/state/trackerCapture";
import eir from "./program-forms/eir/index.js";
import fddAdr from "./program-forms/fdd-adr/index.js";
import deliveryRegistry from "./program-forms/delivery-registry/index.js";
import ancPnc from "./program-forms/antenatal-postnatal/index.js";
import eirLocales from "./locales/eir.js";
import fddAdrLocales from "./locales/fddAdr.js";
import ipdDischargeSummaryLocales from "./locales/ipdDischargeSummary.js";
import ClientRegistrySearchButton from "./common/ClientRegistrySearchButton/ClientRegistrySearchButton.jsx";
import MchLayout from "./program-forms/common/MchLayout/MchLayout.jsx";
import ChrTrackerLayout from "./layout/ChrTrackerLayout/ChrTrackerLayout.jsx";
import MccodLayout from "./program-forms/common/MccodLayout/MccodLayout.jsx";
import familyPlanning from "./program-forms/family-planning/index.js";
import abortionDetails from "./program-forms/abortion-details/index.js";
import postnatalCare from "./program-forms/postnatal-care/index.js";
//dataSet locales
import EirCompleteButton from "./program-forms/common/tracker/EirCompleteButton/EirCompleteButton.jsx";
import VillageSelectorWithoutHandler from "./program-forms/common/tracker/VillageSelector/VillageSelectorWithoutHandler.jsx";
import customHooks from "./hooks.jsx";
import EirProfile from "./program-forms/eir/Profile.jsx";
import ipdDischargeSummary from "./program-forms/ipd-discharge-summary/index.js";
//program locales
import deliveryRegistryLocales from "./locales/deliveryRegistry.js";
import antenatalPostnatalLocales from "./locales/antenatalPostnatal.js";
import familyPlanningLocales from "./locales/familyPlanning.js";
import abortionDetailsLocales from "./locales/abortionDetails.js";
import postnatalCareLocales from "./locales/postnatalCareLocales.js";
const customForms = {
  u1Na9wCGY6d: postnatalCare,
  ck0rft9jVlF: ipdDischargeSummary,
  Yj9cJ34AXw6: eir,
  AQBx2QVBvRH: fddAdr,
  AyPkCOMmgdd: deliveryRegistry,
  fflLsS1lm3g: ancPnc,
  PBLmYwloRHu: familyPlanning,
  vqNgkw4gfw7: abortionDetails
};

const hooks = customHooks;

const locales = {
  u1Na9wCGY6d: postnatalCareLocales,
  Yj9cJ34AXw6: eirLocales,
  AQBx2QVBvRH: fddAdrLocales,
  ck0rft9jVlF: ipdDischargeSummaryLocales,
  AyPkCOMmgdd: deliveryRegistryLocales,
  fflLsS1lm3g: antenatalPostnatalLocales,
  PBLmYwloRHu: familyPlanningLocales,
  vqNgkw4gfw7: abortionDetailsLocales
};

const customLocales = {
  en: {
    searchFromClientRegistry: "Search (from Client Registry)",
    edit: "Edit",
    bloodPressure: "Blood pressure",
    clientNotFound: "Sorry, this client cannot be found in the system, you can either try more search criterias or register new client.",
    searchAgain: "Search again",
    doEnroll: "This client will be enrolled to {{program}} in the facility: {{facility}}. Are you sure you want to continue?",
    enrolled: "This client is already enrolled to {{program}}. Click OK to open the form",
    profile: "Profile",
    searchOptions: "Search options",
    clientRegistryRegister: "Register",
    last4ClientHealthIdDigits: "Last 4 digits of Client Health ID",
    childUniqueIdWarning1: "This field is automatically generated by the system",
    chrDocument: "Client Health Registry and MCH Tracker programs",
    howChrWorks: "1. How Client Health Registry works",
    howToEditAPersonInChr: "2. How to edit a person in Client Health Registry",
    howToDeleteAPersonInChr: "3. How to delete a person in Client Health Registry",
    checkingClientHealthId: "Checking Client Health ID...",
    healthIdSearchHelper: "Please carefully input the correct ID format to search on this field (xxxxxxxx-x-xxxx)",
    cvidSearchHelper: "Please carefully input the correct System CVID format to search on this field (Hxxxx-x-xxxxx)",
    searchError:
      "Something went wrong, sorry for the inconvenience, please note your search criterias down and report to system administrator, thank you.",
    mccodHelper: "Please use Cause Of Death App to work with MCCOD program, click this",
    link: "link",
    currentAddress: "Current address",
    clientHealthIdWarning1: "This field is automatically generated by the system",
    clientHealthIdWarning2: "You will see the Client Health ID in the next page after the registration is completed",
    cannotSaveMissingMandatoryFields: "Cannot save this record because these mandatory fields are missing",
    noErrors: "No errors, you can save this record!",
    invalidPhoneNumber: "Invalid phone number",
    addNewEventWarning: "Previous events must be completed before creating new event.",
    editProfileConfirmation: "Are you sure you want to edit this information profile?",
    last4Digits: "Last 4 digits",
    dob: "Date of birth",
    sex: "Sex"
  },
  lo: {
    searchFromClientRegistry: "ຄົ້ນຫາ ( ຈາກ Client Registry )",
    edit: "ແກ້ໄຂ",
    bloodPressure: "ຄວາມດັນເລືອດ",
    clientNotFound:
      "ຂໍອະໄພ, ບໍ່ສາມາດພົບຂໍ້ມູນຂອງຜູ້ເຂົ້າມາຮັບບໍລິການສາທາລະນະສຸກ, ທ່ານສາມາດລອງຊອກຫາເພີ່ມເຕີມໂດຍນຳໄຊ້ມາດຖານອື່ນແທນຫຼື ລົງທະບຽນໃໝ່ໃຫ້ຜູ້ມາຮັບບໍລິການສາທາລະນະສຸກ.",
    searchAgain: "ຄົ້ນຫາອີກຄັ້ງໜຶ່ງ",
    doEnroll:
      "ຜູ້ມາຮັບບໍລິການສາທາລະນະສຸກຜູ້ນີ້ຈະໄດ້ຖືກລົງທະບຽນເຂົ້າໃນໂປຣແກຣມ {{program}} ຢູ່ທີ່ສະຖານທີ່ບໍລິການ: {{facility}}. ທ່ານຢາກສືບຕໍ່ລົງທະບຽນບໍ່?",
    enrolled: `ຜູ້ມາຮັບບໍລິການຄົນນີ້ໄດ້ຖືກລົງທະບຽນເຂົ້າໃນສາຍງານ {{program}}. ໃຫ້ທ່ານກົດໃສ່ "ຕົກລົງ" ເພື່ອເປີດຟອມຂຶ້ນມາ.`,
    profile: "ຂໍມູນຂອງແມ່",
    searchOptions: "ຕົວເລືອກການຄົ້ນຫາ",
    clientRegistryRegister: "ລົງທະບຽນ",
    last4ClientHealthIdDigits: "ເລກທ້າຍ 4 ຕົວຂອງລະຫັດສຸຂະພາບ",
    childUniqueIdWarning1: "ຫ້ອງນີ້ລະບົບຈະສ້າງໃຫ້ອັດຕະໂນມັດ",
    chrDocument: "Client Health Registry and MCH Tracker programs",
    howChrWorks: "1. How Client Health Registry works",
    howToEditAPersonInChr: "2. How to edit a person in Client Health Registry",
    howToDeleteAPersonInChr: "3. How to delete a person in Client Health Registry",
    checkingClientHealthId: "Checking Client Health ID...",
    healthIdSearchHelper: "ກະລຸນາປ້ອນລະຫັດສຸຂະພາບໃຫ້ຖືກຕາມຮູບແບບທີ່ກຳນົດໄວ້ເພື່ອຄົ້ນຫາ (xxxxxxxx-x-xxxx)",
    cvidSearchHelper: "ໃຫ້ທ່ານກວດສອບຢ່າງລະອຽດທຸກຄັ້ງກ່ອນທີ່ຈະຄົ້ນຫາດ້ວຍລະຫັດໂຄວິດ, ຕ້ອງຕື່ມໃຫ້ຖືກຕາມຮູບແບບຂອງລະຫັດ ຕົວຢ່າງ (Hxxxx-x-xxxxx)",
    searchError: "ການຄົ້ນຫາມີບັນຫາ, ຂໍອະໄພໃນຄວາມບໍ່ສະດວກ.  ກະລຸນາຈົດວິທີການຄົ້ນຫາຄັ້ງນີ້ໄວ້ແລ້ວແຈ້ງຫາທີມງານຄຸ້ມຄອງລະບົບຕື່ມ.",
    mccodHelper: "Please use Cause Of Death App to work with MCCOD program, click this",
    link: "link",
    currentAddress: "ທີ່ຢູ່ປະຈຸບັນ",
    clientHealthIdWarning1: "ຫ້ອງນີ້ລະບົບຈະສ້າງໃຫ້ອັດຕະໂນມັດ",
    clientHealthIdWarning2: "ລະຫັດຈະຖືກສ້າງຂຶ້ນໃຫ້ໂດຍອັດຕະໂນມັດຢູ່ຫນ້າຕໍ່ໄປຫລັງຈາກທ່ານລົງທະບຽນຜູ້ມາຮັບບໍລິການຮຽບຮ້ອຍແລ້ວ.",
    cannotSaveMissingMandatoryFields:
      "ລະບົບບໍ່ສາມາບດບັນທຶກຂໍ້ມູນທີ່ທ່ານປ້ອນໄດ້ເທື່ອເພາະວ່າຂໍ້ມູນທີ່ຈຳເປັນຍັງບໍ່ທັນໄດ້ຕື່ມໃສ່, ໃຫ້ທ່ານກວດຄືນເບິ່ງຕື່ມວ່າມີຂໍ້ມູນໃດທີ່ຍັງບໍ່ໄດ້ປ້ອນເທື່ອ",
    noErrors: "ຂໍ້ມູນຖືກຕື່ມຄົບຖ້ວນແລ້ວ, ທ່ານສາມາດບັນທຶກໄດ້ເລີຍ!",
    invalidPhoneNumber: "Invalid phone number",
    addNewEventWarning: "ຕ້ອງສຳເລັດເຫດການທີ່ຜ່ານມາກ່ອນຈື່ງສາມາດສ້າງເຫດການໃໝ່ໄດ້.",
    editProfileConfirmation: "ທ່ານໝັ້ນໃຈບໍວ່າຕ້ອງການແກ້ໄຂຂໍ້ມູນສ່ວນຕົວ?",
    last4Digits: "Last 4 digits",
    dob: "ວັນເດືອນປີເກີດ",
    sex: "ເພດ"
  }
};

const customEventListColumns = {};

const multiOrgUnitsDataSets = [];

const customTimelineFields = [
  {
    programStage: "DlhoBsu5Cp8",
    fields: [
      {
        style: { fontWeight: "bold" },
        type: "dataElement",
        field: "NtnqZYgVfZ5"
      }
    ]
  }
];

const customProgramRules = {
  QQkFwiPkEBv: [
    {
      condition: "currentEvent.disabled === true",
      programRuleActions: [
        {
          programRuleActionType: "SHOWERROR",
          dataElement: { id: "S3FyEAI34OA" },
          content: ""
        }
      ]
    }
  ]
};

const customEventListSorts = {};
const documents = [
  {
    label: "howToSeeTheDocuments",
    type: "googleDoc",
    url: "https://docs.google.com/document/d/e/2PACX-1vT3O9L0CxdmRiJft5CwZ07WsddTOg1slasUVyFgKxnPdCKyIMYOr5mJifnAOfoE4-pMzM5s_7IGW3Rl/pub?embedded=true"
  },
  {
    label: "faqs",
    type: "googleDoc",
    url: "https://docs.google.com/document/d/e/2PACX-1vSY3C90x9gVhqCoMB5U2xZw6JGhkMULLo2eTZjckvw-uCT5bAXADvkWnxuTa3qs8sXxiW019Z46hU3n/pub?embedded=true"
  },
  {
    label: "eirManual",
    type: "docx",
    url: "https://docs.google.com/document/d/e/2PACX-1vQ7kJ4TKr9Fp3UV02zo1k5MwR7hHbeaithBDo63xFpQYlzTxKNxzTXKsbbWSD81BorlPqXrLOT93aaS/pub"
  },
  {
    label: "comingSoon",
    type: "text"
  }
];

const eventSaveInjections = [];

const customTrackerCompleteButtons = {
  Yj9cJ34AXw6: EirCompleteButton
};

const customTeiListColumns = {
  hr56o6I5n6p: [
    {
      type: "attribute",
      id: "RH44eXu8Wwl",
      render: (tei, t) => {
        const foundEnrollment = tei.enrollments.find((enr) => enr.program === "hr56o6I5n6p" && enr.status === "ACTIVE");
        const events = _.sortBy(foundEnrollment.events, ["eventDate"]).reverse();
        const event = events[0];
        const foundAttribute = tei.attributes.find((attr) => attr.attribute === "RH44eXu8Wwl");
        if (event) {
          const foundTypeOfVisit = event.dataValues.find((dv) => dv.dataElement === "NtnqZYgVfZ5");
          if (foundTypeOfVisit && foundTypeOfVisit.value === "Complete") {
            return t("complete");
          }
          return foundAttribute ? foundAttribute.value : "";
        } else {
          return foundAttribute ? foundAttribute.value : "";
        }
      }
    }
  ]
};

const teiSearchSections = {
  hr56o6I5n6p: [
    {
      label: "childDetails",
      trackedEntityAttributes: [
        "zZoGQEghrHp",
        "IEE2BMhfoSc",
        "IBLkiaYRRL3",
        "tQeFLjYbqzv",
        "DmuazFb368B",
        "r8bZppSsIvR",
        "oVwa5LfjnvA",
        "UNiaP6Oz7Mv"
      ]
    },
    {
      label: "guardianDetails",
      trackedEntityAttributes: ["Y58VlT2JZ0h", "rkvu8WOjGun", "hyjuL8jlDbr"]
    },
    {
      label: "treatmentDetails",
      trackedEntityAttributes: ["oWFcp8NFmOV", "B8PuwTK2vGJ"]
    }
  ]
};
const teiFilterSections = {};

const customTeiFilterFields = {
  hr56o6I5n6p: {
    r8bZppSsIvR: (currentTeas, filters, changeFilter) => {
      const foundProvince = currentTeas.find((tea) => tea.id === "r8bZppSsIvR");
      const foundDistrict = currentTeas.find((tea) => tea.id === "oVwa5LfjnvA");
      const foundVillage = currentTeas.find((tea) => tea.id === "UNiaP6Oz7Mv");
      const values = ["r8bZppSsIvR", "oVwa5LfjnvA", "UNiaP6Oz7Mv"].map((tea) => {
        const found = filters.find((f) => f.id === tea);
        if (found) {
          return found.value;
        } else {
          return "";
        }
      });
      return (
        <VillageSelectorWithoutHandler
          labels={[foundProvince.displayFormName, foundDistrict.displayFormName, foundVillage.displayFormName]}
          values={values}
          change={(values) => {
            changeFilter(foundProvince, values[0] ? values[0].value : "");
            changeFilter(foundDistrict, values[1] ? values[1].value : "");
            changeFilter(foundVillage, values[2] ? values[2].value : "");
          }}
        />
      );
    },
    oVwa5LfjnvA: (currentTeas, filters, changeFilter) => {
      return null;
    },
    UNiaP6Oz7Mv: (currentTeas, filters, changeFilter) => {
      return null;
    }
  }
};
const customTeiSearchFields = {
  hr56o6I5n6p: {
    r8bZppSsIvR: (searchableTeas, criterias, changeCriteria) => {
      const foundProvince = searchableTeas.find((tea) => tea.id === "r8bZppSsIvR");
      const foundDistrict = searchableTeas.find((tea) => tea.id === "oVwa5LfjnvA");
      const foundVillage = searchableTeas.find((tea) => tea.id === "UNiaP6Oz7Mv");
      const values = [criterias[foundProvince.id] || "", criterias[foundDistrict.id] || "", criterias[foundVillage.id] || ""];
      return [
        <br />,
        <VillageSelectorWithoutHandler
          labels={[foundProvince.displayFormName, foundDistrict.displayFormName, foundVillage.displayFormName]}
          values={values}
          change={(values) => {
            changeCriteria(foundProvince.id, values[0] ? values[0].value : "");
            changeCriteria(foundDistrict.id, values[1] ? values[1].value : "");
            changeCriteria(foundVillage.id, values[2] ? values[2].value : "");
          }}
        />
      ];
    },
    oVwa5LfjnvA: (searchableTeas, criterias, changeCriteria) => {
      return null;
    },
    UNiaP6Oz7Mv: (searchableTeas, criterias, changeCriteria) => {
      return null;
    }
  }
};

const transferEvent = async (currentTei, currentEnrollment, currentEvent) => {
  let foundDataValue = currentEvent.dataValues.find((dv) => dv.dataElement === "uoKJZliHVhB");

  if (foundDataValue) {
    let tei = { ...currentTei };
    let enrollment = { ...currentEnrollment };
    enrollment.orgUnit = foundDataValue.value;
    tei.orgUnit = foundDataValue.value;
    let foundProgramOwner = tei.programOwners.find((po) => po.program === "hr56o6I5n6p");
    let programOwners = { ...foundProgramOwner };
    if (foundProgramOwner) {
      programOwners.ownerOrgUnit = foundDataValue.value;
      tei.programOwners = tei.programOwners.filter((e) => !e.program === "hr56o6I5n6p");
      tei.programOwners.push(programOwners);
    }
    const updateTei = await push("/api/trackedEntityInstances?strategy=CREATE_AND_UPDATE", {
      trackedEntityInstances: [tei]
    });
    const updateEnrollment = await push("/api/enrollments?strategy=CREATE_AND_UPDATE", {
      enrollments: [enrollment]
    });
    const updateOwnership = await push(
      `/api/tracker/ownership/transfer?trackedEntityInstance=${tei.trackedEntityInstance}&program=hr56o6I5n6p&ou=${foundDataValue.value}`,
      {},
      "PUT"
    );
    useTrackerCaptureStore.setState({
      layout: { layout: "layout1", disableCompleteButton: false }
    });
    useTrackerCaptureStore.setState({
      data: {
        selectedProgramStage: null,
        selectedEvent: null,
        currentTei: null,
        currentEnrollment: null,
        currentEvents: null,
        teiFilter: useTrackerCaptureStore.getState().data.teiFilter
      }
    });
  }
};

const additionalCompleteHandlers = {
  DlhoBsu5Cp8: async (currentTei, currentEnrollment, currentEvent) => {
    if (currentEvent.status === "COMPLETED") {
      await transferEvent(currentTei, currentEnrollment, currentEvent);
    }
  }
};

const customProfile = {
  Yj9cJ34AXw6: EirProfile
};

const trackerFormTypes = {
  Yj9cJ34AXw6: ["tabular", "noBlur"],
  ck0rft9jVlF: ["noBlur", "tabStage", "tabular"],
  fflLsS1lm3g: ["noBlur", "tabStage", "tabular"],
  u1Na9wCGY6d: ["noBlur", "tabStage", "tabular"],
  PBLmYwloRHu: ["noBlur", "tabStage", "tabular"],
  vqNgkw4gfw7: ["noBlur", "tabStage", "tabular"]
};

const allowedPrograms = ["Yj9cJ34AXw6", "ck0rft9jVlF", "AyPkCOMmgdd", "fflLsS1lm3g", "PBLmYwloRHu", "vqNgkw4gfw7", "u1Na9wCGY6d", "ogrOUKoSaWA"];
const modes = [
  //"eventCapture",
  //"dataEntry",
  "trackerCapture"
];

const customControlBarComponent = {
  ck0rft9jVlF: ClientRegistrySearchButton,
  AyPkCOMmgdd: ClientRegistrySearchButton,
  fflLsS1lm3g: ClientRegistrySearchButton,
  u1Na9wCGY6d: ClientRegistrySearchButton,
  PBLmYwloRHu: ClientRegistrySearchButton,
  vqNgkw4gfw7: ClientRegistrySearchButton
};

const customTrackerLayout = {
  AyPkCOMmgdd: ChrTrackerLayout,
  ogrOUKoSaWA: MccodLayout,
  fflLsS1lm3g: ChrTrackerLayout,
  vqNgkw4gfw7: ChrTrackerLayout,
  PBLmYwloRHu: ChrTrackerLayout,
  ck0rft9jVlF: ChrTrackerLayout,
  u1Na9wCGY6d: ChrTrackerLayout
};

export default {
  customControlBarComponent,
  customForms,
  customEventListColumns,
  locales,
  customLocales,
  multiOrgUnitsDataSets,
  hooks,
  customProgramRules,
  customTimelineFields,
  customEventListSorts,
  documents,
  trackerFormTypes,
  eventSaveInjections,
  customTrackerCompleteButtons,
  customTeiListColumns,
  teiFilterSections,
  teiSearchSections,
  customTeiFilterFields,
  customTeiSearchFields,
  additionalCompleteHandlers,
  modes,
  customProfile,
  allowedPrograms,
  customTrackerLayout
};
